### PR TITLE
Document Recognizer.ErrorListeners

### LINKED ISSUE #156: Not intuitive work with ErrorListener in parser or lexer
The following lines do nothing:

``` C#
antlr4Parser.ErrorListeners.Clear();
antlr4Parser.ErrorListeners.Add(errorListener);
```

We should use this instead:

``` C#
antlr4Parser.RemoveErrorListeners();
antlr4Parser.AddErrorListener(errorListener);
```

Maybe it's better to make member `ErrorListeners` private or readonly?

### PR DESCRIPTION
**Pull request by sharwell**
Closes #156 

/cc @KvanTTT

### CODE REVIEW

**Comment by KvanTTT** [comment]
Maybe use [ObsoleteAttribute](https://msdn.microsoft.com/en-us/library/system.obsoleteattribute(v=vs.110).aspx)?

**Comment by sharwell** [comment]
@KvanTTT There are several places that currently use this. I'll see if I can resolve those in another way so I can add `[Obsolete]`.

**Comment by KvanTTT** [comment]
In this places `#pragma warning disable` directive can be used as I guess: [Disabling OBSOLETE error in C#](http://stackoverflow.com/questions/10608309/disabling-obsolete-error-in-c-sharp) :)

**Comment by sharwell** [comment]
It's actually not that hard to avoid using `ErrorListeners`. The bigger question I have is what are the chances that someone is currently using this (and not modifying it)?

**Comment by KvanTTT** [comment]
I think this is not a big problem. At the worst case, it's possible to use an older version or easily modify the code. Moreover, Java runtime have a private error listeners and public `removeErrorListener`, `addErrorListener` methods: https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/Recognizer.java#L30.

**Comment by sharwell** [comment]
> I think this is not a big problem. At the worst case, it's possible to use an older version or easily modify the code. 

I agree, and it's totally possible that no one is currently relying on this method. That said, one of the reasons some larger users choose my fork is I put substantial effort into trying to prevent breaking changes from ever causing users to choose between an older version or changing the code. If it's possible to make upgrading a painless experience, then I'm willing to go out of my way to make that a reality. 👍 

> Moreover, Java runtime have a private error listeners ...

Java has the corresponding method but uses generics magic to make it effectively read only.

https://github.com/antlr/antlr4/blob/58b7b717310c360d402c2fe9e57c9c58db1168e2/runtime/Java/src/org/antlr/v4/runtime/Recognizer.java#L230-L232

**Comment by osre77** [comment]
I actually rely on this property and get the obsolete Message now.
May I suggest to remove the obsolete Attribute, and return a ReadOnlyCollection wrapping the internal list. By this one can enumerate the listeners, but not adding and remove them, just as intended.

**Pull request merged**
