### PR TITLE
Support for ASP.Net Core in Modern PCL Projects

### PR DESCRIPTION
**Pull request by afscrome**
Attempting to reference the antlr4 package in a modern PCL targeting ASP.Net core fails with the error shown bleow.  This pull request adds support for generating a "dotnet" target to support the DNXCore PCL target, allowing Antlr4 to be referenced by modern PCLs.

This is work in progress because the build tools don't currently work with the Modern PCL project.  At present, the XPathLexer has been manually generated, but need to get it auto generating at built time before merging this pull request.

```
Restoring packages for 'PCLTest'.
Restoring packages for C:\Alex\Documents\visual studio 2015\Projects\PCLTest\PCLTest\project.json...
All packages are compatible with .NETPlatform,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with UAP,Version=v10.0.
Antlr4.Runtime 4.5.0-alpha002 is not compatible with DNXCore,Version=v5.0.
Some packages are not compatible with DNXCore,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6 (win-x86).
All packages are compatible with .NETFramework,Version=v4.6 (win-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x86).
All packages are compatible with UAP,Version=v10.0 (win10-x86-aot).
All packages are compatible with UAP,Version=v10.0 (win10-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x64-aot).
All packages are compatible with UAP,Version=v10.0 (win10-arm).
All packages are compatible with UAP,Version=v10.0 (win10-arm-aot).
Antlr4.Runtime 4.5.0-alpha002 is not compatible with DNXCore,Version=v5.0 (win7-x86).
Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86).
Antlr4.Runtime 4.5.0-alpha002 is not compatible with DNXCore,Version=v5.0 (win7-x64).
Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64).
Package restore failed for 'PCLTest'.
Package restore failed. Rolling back package changes for 'PCLTest'.
========== Finished ==========
```

### CODE REVIEW

**Comment by sharwell** [comment]
:thought_balloon: Based on [this article](https://oren.codes/2015/07/29/targeting-net-core/), it looks like you should be able to support DNX by simply updating the **.nuspec** file to include a second copy of the file in **portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1** in a **dotnet** folder.

```xml
<file src="..\runtime\CSharp\Antlr4.Runtime\bin\portable-net45\$Configuration$\Antlr4.Runtime.dll" target="lib\dotnet"/>
<file src="..\runtime\CSharp\Antlr4.Runtime\bin\portable-net45\$Configuration$\Antlr4.Runtime.pdb" target="lib\dotnet"/>
<file src="..\runtime\CSharp\Antlr4.Runtime\bin\portable-net45\$Configuration$\Antlr4.Runtime.xml" target="lib\dotnet"/>
```

**Comment by afscrome** [comment]
Interesting, hadn't seen that blog post.  For the dependencies, I believe they would be those defined in 
https://github.com/afscrome/antlr4cs/blob/master/runtime/CSharp/Antlr4.Runtime/Antlr4.Runtime.dotnet.project.json .  That means that adding the new project has an advantage over reusing "portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1" in that it gives us compile time validation of dependencies - if we're missing dependencies, the dotnet project will fail to compile.

(N.B. this currently doesn't create a package because I've got one last issue to resolve - for some reason, the .props file isn't being imported.  If I manually copy the content of that file into `Antlr4.Runtime.dotnet.csproj`, then the build works)

**Comment by afscrome** [comment]
So this is now working, although there is one slightly nasty hack.  

The build process currently has a circular dependency - the Antlr4.Runtime builds rely on the Antlr4 nuget package (which in turn relies on the Antlr4.Runtime build).  This is needed to generate the XPath lexer.

For the existing projects, this doesn't cause any problems because whilst the Antlr4.Runtime nuget package is referenced, the Antlr4.Runtime dll reference has been removed from the csproj.  For the new project.json based project, this no longer works because the nuget package references & the project references have been unified into a single concept.

The current pull requests cheats here - the new project doesn't reference the nuget package directly, however it relies on the package being imported by other projects in the solution in order to get the msbuild target & props file for the lexer build tools.  Whilst it's messy, I'm not sure of a better approach.  Two alternatives I though of (and rejected) are as follow - it would be great to hear if you have any other ideas.

1. Split the Antlr4 package into two packages.  An "Antlr4.BuildTools" package which only includes the build tools (without the Antlr4.Runtime reference), then the Antlr4 package becomes an empty package, referencing "Antlr4.BuildTools" and "Antlr4.Runtime".   This seems messy because it's creating an extra package to maintain 
2. Don't use the Antlr4 build package, and instead add a custom command to the Pre-Build event to call the antlr code generator directly.  This is a bit nasty because we're then loosing the great Visual Studio integration.

**Comment by afscrome** [comment]
@sharwell This is ready for merge now.

**Comment by afscrome** [comment]
@sharwell I've had another go at this with rc1 based on http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-1.html . 

The biggest thing missing from the work so far is wiring up the code generation for g4 files.  (For now I've manually committed the xpathlexer, but that obviously needs to change).  I had a very quick try to use the  existing task but couldn't get it to work (Not sure at this stage whether it's me being silly, or whether the build task won't work with xproj files).  Part of me however wonders whether the msbuild task is the right way to - using an msbuild task is actually the right approach for the cross platform world?  The msbuild task won't work with `dnu pack` for example.  Thoughts?

Other small things that need further work:

[ ] Build scripts likely need some work 
[ ] Can't get net35-cf to work in project.json - fails with a "Sequence contains no elements" error - may be a bug in the `dnu` but needs more investigation
[ ] Currently struggling getting the "portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1" binary to work.  Not sure if it even matters as I'm not sure there's anything in that build that shouldn't be covered by "portable-net4+sl5+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1".

**Comment by sharwell** [comment]
I'm planning to take a deeper look at this (and other issues/PRs) starting in the middle of this month. :smile:

**Comment by simmdan** [comment]
Any news on this front?  My team is in the process of switching to CoreCLR so that we can go cross-platform, and this is crucial for us.  I am more than happy to help if I can.

**Comment by sharwell** [comment]
@afscrome @simmdan Initial support for this should now be included in **4.5.3.1-beta001**. Can you try it out and let me know if you encounter problems?

**Comment by afscrome** [comment]
So I'm struggling to get this working in a .net core project - specifically getting the build tool to generate source code from the .g4 files .

Any recommendations at to how to get the code generation working with a .Net core project- I'm currently looking at using a grunt file as described at https://github.com/tunnelvisionlabs/antlr4cs/issues/110#issuecomment-109092219 , but wondering if you had any better ideas.

**Comment by sharwell** [comment]
@afscrome Can you open an issue for that specifically? Now that the dependencies can be added it seems like that is a separate step.

**Comment by rjrudman** [comment]
As an alternative to the gruntfile in #110 
1. Include the following in your `project.json`:

```
"scripts": {
	"precompile": "generateGrammar.bat"
},
"tools": {
	"Antlr4.CodeGenerator": "4.5.4-beta001"
},
```

Create a file named `generateGrammar.bat` in your projects directory, with the following:
```
echo Generating grammar parsers...
@echo OFF
java -cp "%HOMEDRIVE%%HOMEPATH%\.nuget\packages\Antlr4.CodeGenerator\4.5.4-beta001\tools\antlr4-csharp-4.5.4-SNAPSHOT-complete.jar" org.antlr.v4.Tool -o -visitor -no-listener -Werror -o Generated -Dlanguage=CSharp_v4_5 INSERT_GRAMMAR_FILE.g4
```

Note this still suffers from the problem of hard-coding the package information.

A better solution may be to create a dotnet tool, put it on NuGet, and you'll end up with something like:

`dotnet ANTLRGenerate {opts}`

**Pull request closed without merging**
