### PR TITLE
Add back the Antlr4 dependency for XPath support

### LINKED ISSUE #144: .Net Core Support
Nuget error when installing for .Net Core console app:
Errors in c:\users\ryanl\documents\visual studio 2015\Projects\ConsoleApp2\src\ConsoleApp2\ConsoleApp2.xproj
    Package Antlr4.Runtime 4.5.3-rc1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Antlr4.Runtime 4.5.3-rc1 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net30 (.NETFramework,Version=v3.0)
      - net35-cf (.NETFramework,Version=v3.5,Profile=CompactFramework)
      - net35-client (.NETFramework,Version=v3.5,Profile=Client)
      - net40-client (.NETFramework,Version=v4.0,Profile=Client)
      - net45 (.NETFramework,Version=v4.5)
      - netcore45 (.NETCore,Version=v4.5)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)

### PR DESCRIPTION
**Pull request by sharwell**
This is (should be!) the final change to bring support for .NET Standard (1.1+).

Closes #144

### CODE REVIEW

**Comment by sharwell** [comment]
@lecode-official With this merged, I'm going to publish release 4.5.3.1-beta001 to NuGet. It should fully support .NET Standard 1.1+. Can you take a look and let me know if you have any problems?

**Comment by ph1ll** [comment]
Many thanks, 4.5.3.1-beta001 works in my .NET Core projects without any need for extra imports :smile:

**Comment by lecode-official** [comment]
@sharwell Thanks for the info, I did not see this comment. I am going to try out the new .NET Standard 1.1 version as soon as possible. I previously tried to use this alternative but I ran into compilation problems. I think the problem was, that I didn't tell Antlr that I was using the alternative C# runtime. Do you have any pointers for me to properly install Antlr4 and compile my grammar on Ubuntu?

**Comment by ph1ll** [comment]
Personally I am only using the Antlr4.Runtime package in my project. In order to generate my grammar in a .NET Core project I have been using `antlr4-csharp-4.5.3-SNAPSHOT-complete.jar` extracted from the nuget package together with a small script:

```
DEL /Q /S Generated
java -jar antlr4-csharp-4.5.3-SNAPSHOT-complete.jar *.g4 -o Generated -Dlanguage=CSharp_v4_5 -package "MyNamespace" -visitor
```

**Comment by sharwell** [comment]
@lecode-official Take a look at #110 as a starting place. It uses some older tooling but hopefully we can use it as a starting point. In the worst case, you can add a reference to the **Antlr4** package so it downloads the code generation tools from NuGet, and then use a separate script to invoke it directly based on the configuration descriptions I listed in #110.

**Pull request merged**
