### PR TITLE
Release/4.6.1 beta001

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by KvanTTT** [comment]
I'm waiting for upcoming 4.7 :)

**Comment by sharwell** [comment]
@KvanTTT Is there something particular you're waiting for (e.g. Unicode changes, tree rewriting)?

**Comment by KvanTTT** [comment]
Mostly I'm waiting for the alternative label bugfix https://github.com/antlr/antlr4/issues/1543 and other less priority symbol bugfixes.

**Comment by sharwell** [comment]
@KvanTTT That bug is already fixed in this release.

**Comment by KvanTTT** [comment]
That's great!  Waiting for nuget package then :)

**Comment by lextm** [comment]
Exception https://github.com/antlr/antlr4/issues/1738, everything looks good.

**Comment by sharwell** [comment]
@lextm Can you file that bug on this repository? This C# target is developed independently from antlr/antlr4.

**Pull request merged**
